name: Static Code Security Analysis

on:
  workflow_call:
    inputs:
      default_branch:
        type: string
        required: true
        description: "Default branch of the repository"
      push_before_sha:
        type: string
      push_base_sha:
        type: string
      pull_base_sha:
        type: string
    secrets:
      GITGUARDIAN_API_KEY:
        required: true
        description: "GitGuardian API key"

jobs:
  code_security:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: GitGuardian - Secrets Detection
        uses: GitGuardian/ggshield/actions/secret@v1.52.2
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
          GITHUB_PUSH_BEFORE_SHA: ${{ inputs.push_before_sha }}
          GITHUB_PUSH_BASE_SHA: ${{ inputs.push_base_sha }}
          GITHUB_PULL_BASE_SHA: ${{ inputs.pull_base_sha }}
          GITHUB_DEFAULT_BRANCH: ${{ inputs.default_branch }}
