name: Deploy to Vercel

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Deployment environment (e.g. production, preview)"
        required: true
    secrets:
      VERCEL_TOKEN:
        description: The Vercel token
        required: true
      VERCEL_ORG_ID:
        description: The Vercel organization ID
        required: true
      VERCEL_PROJECT_ID:
        description: The Vercel project ID
        required: true
    outputs:
      status:
        description: "The status of the deployment"
        value: ${{ jobs.deploy.outputs.status }}
      url:
        description: The URL of the deployment
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
      url: ${{ steps.deployment.outputs.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build Project
        run: pnpm build

      - name: Deploy to Vercel
        id: deployment
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          DEPLOY_CMD="vercel --token=${{ secrets.VERCEL_TOKEN }}"
          [[ '${{ inputs.environment }}' == 'production' ]] && DEPLOY_CMD+=" --prod"
          DEPLOY_OUTPUT=$($DEPLOY_CMD --yes)
          echo "$DEPLOY_OUTPUT"
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep -oE "https?://[a-zA-Z0-9./_-]+" | tail -n 1)

          if [ -z "$DEPLOY_URL" ]; then
            echo "Failed to extract deployment URL."
            exit 1
          fi

          echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
