name: Static Dependency Security Analysis

on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: "Whether the Snyk scan should continue the workflow on detected vulnerabilities"
        default: false
      report:
        type: boolean
        description: "Whether to report the results to GitHub Code Scanning"
        default: false
    secrets:
      SNYK_TOKEN:
        required: true
        description: "Snyk token"

permissions:
  security-events: write # Required to upload SARIF files
  actions: read # Required to download actions
  contents: read # Required to checkout the code

jobs:
  deps_security:
    name: Deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@v1.0.0
        continue-on-error: ${{ inputs.continue-on-error }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >-
            --severity-threshold=high
            --fail-on=upgradable
            --prune-repeated-subdependencies
            --sarif-file-output=snyk.sarif
            --all-projects

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4.37.3
        if: ${{ inputs.report }}
        with:
          sarif_file: snyk.sarif
